name: check
on: 
  push:
    paths:
    - "lists/*"
  pull_request:
    paths:
    - "lists/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check
      run: python scripts/lint-lists.py lists/
